eureka:
  client:
    service-url:
      defaultZone: http://111.231.119.253:8761/eureka
  instance:
    ip-address: 111.231.119.253
    prefer-ip-address: true
spring:
  application:
    name: keygen-service
server:
  port: 8087
zk:
  host: 127.0.0.1