eureka:
  client:
    service-url:
      defaultZone: http://111.231.119.253:8761/eureka
  instance:
    ip-address: 111.231.119.253
    prefer-ip-address: true
spring:
  application:
    name: keygen-service
  zipkin:
    base-url: http://106.14.163.235:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8087
zk:
  host: 127.0.0.1
