eureka:
  client:
    service-url:
      defaultZone: http://111.231.119.253:8761/eureka
spring:
  application:
    name: api-gateway
  datasource:
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/snailmall
    username: root
    password: root
redis:
  host: 111.231.119.253
  port: 6379
  max-idle: 5
  max-total: 10
  max-wait-millis: 3000
server:
  port: 8079
zuul:
  routes:
    category:
      path: /category/**/
      serviceId: category-service
      sensitiveHeaders:
    user:
      path: /user/**/
      serviceId: user-service
      sensitiveHeaders:
