server:
  port: 8761
spring:
  application:
    name: snailmall-eureka-server-2
eureka:
  client:
    service-url:
      defaultZone: http://111.231.119.253:8761/eureka
  server:
    enable-self-preservation: false